TUM-DAML/seml

seml/database_utils.py

`json_normalize` is called from the wrong sub-package. It should be called from `pandas.io.json` instead of `pandas.io.jsonpickle`. Reference: [Pandas API](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html)
Fixes calling `json_normalize` function in `database_utils.py`

json_normalize call bug fix

---

requirements.txt
seml/database_utils.py
seml/settings.py

Introduce a settings file (a la [Sacred](https://github.com/IDSIA/sacred/blob/master/sacred/settings.py)) as a central place for different 'constants' such as the location of the MongoDB config file.
@klicperajo let me know what you think. I've encountered the case here at Stanford that I can't put the config into the home directory so then I have to go into the `SEML` code to hack in a different path, which is really ugly. Plus, we might have more settings/constants like this so I think it's a good idea to have a central place.

Create central settings file

---

seml/database_utils.py
seml/main.py
seml/queue_experiments.py

Computes a hash value of the config dict using Python's `hashlib` to store in each experiment entry. Creates an index over `config_hash` to enable fast search while scanning for duplicates.

faster duplicate filtering via hashes of the config dict

---

requirements.txt

The old requirement for `jsonpickle` does not include `jsonpickle.ext.pandas` which is requries by the latest version of `sacred`.
Also the latest version of `sacred` requires `jsonpickle` to be `<2.0,>=1.2`.

Update jsonpickle requirement

---

examples/example_config.yaml
examples/example_experiment.py
requirements.txt
seml/database_utils.py
seml/get_experiment_command.py
seml/main.py
seml/misc.py
seml/queue_experiments.py
seml/start_experiments.py

Uploads an experiment's source files to the MongoDB upon queueing. We check which files from the project are imported by the experiment and upload these. When running an experiment, we download the stored sources to a temp directory and run the files from there. 
This prevents that a queued experiment might use source files that are different from when the experiment was queued.  
* We need to know the base path of the project in order to know which imported modules belong to the experiment's project. Therefore in the `seml` dict we now store the `project_root_dir`.
* References to the source files are stored under `seml.source_files` in an experiment's database entry.

Upload files when queueing

---

README.md
mongodb.config.example
seml/config.py
seml/database.py
seml/main.py
seml/manage.py
seml/parameters.py
seml/prepare_experiment.py
seml/settings.py
seml/sources.py
seml/start.py

Adds the command `seml --configure`, which prompts the user to provide their MongoDB credentials. Therefore the users no longer have to manually create directories / files. The new location of the config file is in the `seml` base directory in the package.
The `config_file` argument in the main file is now optional (`nargs='?'`). This was necessary in order to be able to run `seml --configure` without an input config file.

Add `seml configure` command to get the MongoDB credentials of the user

---

examples/README.md
examples/example_config.yaml
seml/config.py
seml/manage.py
seml/prepare_experiment.py
seml/queuing.py
seml/slurm_template.sh
seml/sources.py
seml/start.py

Treat all paths as relative either to the `project_root_dir` (if provided) or else the `config_dir`. This way, it does not matter from which directory the `seml` commands are run.
`executable` in the YAML file should now be relative to the project root dir.

Treat paths as relative to either project root dir or the config_dir.

---

seml/queuing.py

Closes #26
When the `slurm` block is missing in the experiment configuration file, the default configuration from `SETTINGS.SLURM_DEFAULT` is taken. Copying the defaults was implemented before, but failed when `slurm_config` was `None` (which is the case when the `slurm` block is missing in the config file).
IMO it makes sense to have a config without the `slurm` block, when one wants to take the default config or when experiments are only run locally.

Fix queuing for configuration file without slurm

---

seml/parameters.py

`np.random.choice` converts the choices into numpy objects. However, numpy booleans are not json serializable which is required during configuration hashing. So you were unable to make a choice between `True` and `False` before this change.

Use stdlib random for the random choice strategy

---

seml/evaluation.py

Add the option to specify a dictionary for more fine grained filtering of the results. If the filter dictionary is specified (by default it is not) ignore the `states` parameter.
Rename `filter` to `db_filter` since `filter` is a Python keyword.

add db_filter to get_results

---

seml/manage.py

Suppose we have a job array with 100 jobs, i.e. a range of [0, 99] for the job array elements.
When we cancel some of those, e.g. using a filter_dict, we can get a `squeue` result that looks like this: `JOBID_[60-89,91-94,96-98]`. The current way to get the tasks of slurm arrays (`get_slurm_arrays_tasks`) only supported a single continuous range. This PR fixes this.

Fix bug encountered when there are disjoint ranges queued for a job array

---

examples/README.md
examples/advanced_example_config.yaml
examples/advanced_example_experiment.py
examples/example_config.yaml
examples/example_experiment.py
examples/logs/.gitignore
seml/config.py
seml/parameters.py
seml/utils.py
tests/resources/config/config_nested_parameter_collections.yaml
tests/resources/config/config_with_all_types.yaml
tests/resources/config/config_with_dict_choice.yaml
tests/resources/config/config_with_duplicate_parameters_1.yaml
tests/resources/config/config_with_duplicate_parameters_2.yaml
tests/resources/config/config_with_duplicate_random_parameters_1.yaml
tests/resources/config/config_with_parameter_collections.yaml
tests/resources/config/config_with_parameter_collections_random.yaml
tests/test_config.py
tests/test_utils.py

Throws an error when the same parameter is re-defined in any two of [`grid`, `fixed`, `random`]. Note that this does **not apply** when the parameter is re-defined in the **same block** (`grid`, `fixed`, or `random`) across levels.
For example, the following **will** throw an error:
```yaml
fixed:
param1: 123
sub_config:
grid:
param1:
type: choice
options:
- 111
- 222
```
while the following configuration will not:
```yaml
fixed:
param1: 123
sub_config:
fixed:
param1: 222
```
Moreover, the error message indicates which parameters at which level are conflicting, e.g.:
```
ERROR: Parameters {'param1'} are defined in both 'grid' and 'fixed' in subconfig 'sub_config'.
ERROR: Found duplicate parameters in subconfig named 'sub_config'. Aborting.
```

Throw an error for parameter re-definitions across different blocks

---

examples/README.md
examples/notebooks/experiment_results.ipynb
seml/main.py
seml/prepare_experiment.py
seml/start.py

Backlog :-)
Major overhaul to local workers and refactoring to `start.py`. Major changes:
* added command `launch-worker` to `main.py`. This can be used to spawn additional local workers.
* added option `--local-steal-slurm` to local jobs. This enables hybrid processing where local workers pop experiments from the Slurm queue. Since we check the database state before actually running the experiment via Slurm, there is no risk of duplicate computation.
* added options `--worker-gpus`,  `--worker-cpus`, and `--worker-environment-vars` to customize local workers.
* Added section on local mode to README.md

Improve local workers

---

seml/config.py
seml/database.py
seml/jupyter_template.sh
seml/main.py
seml/manage.py
seml/network.py
seml/prepare_experiment.py
seml/slurm_template.sh
seml/start.py
setup.py
tests/test_config.py

New debugging capabilities:
- Debugging now works on Slurm! We do this by starting an interactive job via `srun`, in which we use the regular local `seml` command.
- New `debug-server` option, which spawns a debug server via [debugpy](https://github.com/microsoft/debugpy), which an IDE (e.g. VS Code) can attach to remotely. This way we get both the convenience of SEML and a full IDE! Unfortunately, PyCharm's remote debugging [doesn't offer a workflow that would work with SEML](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html) and is therefore incompatible with this.
- Fixed some bugs with debugging, which were introduced when overhauling local workers
- Renamed `--dry-run` to `--print-command`
- Changed `subprocess.check_X` to `subprocess.run`, as officially …

Slurm debug

---

examples/example_config.yaml
seml/config.py
seml/start.py
tests/resources/config/config_with_duplicate_parameters_3.yaml
tests/test_config.py

Users defining the same parameter twice without realizing it.
This disallows _all_ duplicate keys. Users can no longer define 2 `fixed` blocks or 2 `grid` blocks on the same level, or abuse the overriding behavior. This doesn't seem restrictive and is imho actually good practise. But it will inevitably break some users' configs.
Users can still redefine a parameter in a sub-config, in which case the precedence should be clear.

New YamlLoader that disallows duplicate keys

---

seml/prepare_experiment.py
seml/sources.py
seml/start.py

This PR fixes all escaping issues including the one from #50. The vscode configuration works as well as seen in the following example.
```yaml
seml:
executable: 'matching_matrix.py'
conda_environment: 'pytorch1.4'
name: 'language_table'
output_dir: '~/logs'
project_root_dir: '.'
slurm:
experiments_per_job: 1
sbatch_options:
mem: 32G
gres: 'gpu:1'
cpus-per-task: 2
time: '0-1:00'
fixed:
ntrain: 10000
niter: 300
lr_half_niter: 100
print_niter: 999999999
ninit: 2500
lr: 500.
dist_cluster: "l2"
kernel: "l2"
reg: 0.05
p_prefix: "/nfs/staff-ssd/lienen/gdn-alignment-data/stanford-scans/p"
language_src: "/nfs/staff-ssd/lienen/gdn-alignment-data/stanford-scans/armadillo.vec"
language_tgt: "/nfs/staff-ssd/lienen/gdn-alignment-data/stanford-scans/dragon.vec"
deterministic:
fixed:
output_r: marten's …
```

Shell escape

---

seml/manage.py
seml/settings.py

It happens to me occasionally that I want to cancel some experiments but missed something in the filter dict causing the cancellation of many experiments. Seml only asks if more than 10 experiments are cancelled while this is a reasonable heuristic if one has few but long-running jobs cancelling 5 may already be unfortunate.
This adds an option that is disabled by default that causes seml to always asks for confirmation before cancelling any job. It can be overwritten in the user settings.

add settings to always confirm cancelling

---

seml/add.py
seml/config.py
seml/main.py
seml/utils.py
test/resources/config/config_with_grid.yaml
test/test_config.py

Co-authored-by: Leon Hetzel
Issue #71 
```bash
seml <collection> add <yaml> -o [<key>=<value>]
```
`<key>` should use the flattened dictionary notation with `.` and `<value>` is evaluated by `eval`.

Add support for overwriting parameters via CLI

---

examples/README.md

replacing the wrong shorthand --ncc with -ncc
None
gives the correct command line argument to add an experiment without code checkpoints in the example README.
Users new to seml might be confused by this.
just a tiny fix

fix no code checkpoint flag in example README

---

seml/parameters.py

Given the following config:
```
random:
samples: 5
seed: 42
a:
type: uniform
min: 0
max: 1
seed: 43
b:
type: uniform
min: 0
max: 1
seed: 44
```
The outer seed overwrites the inner seeds.
Reversing the if-statements [1] solves the problem.
[1] https://github.com/TUM-DAML/seml/blob/master/seml/parameters.py#L79
Not sure if you really want to reset the outer seed for every parameter. Just setting the outer seed once should be sufficient. But seems like this requires a larger fix, since the inner seeds then overwrite the outer seed again.

Random config: reverse if-statements

---

seml/observers.py

Closes #91 
The fix changes how the API token is set depending on the function argument. And should fix issue #91.
The PR also implements, that the example setting for the token in the settings.py is ignored. Otherwise the Neptune API token will never be read from the environment.

Fix neptune api token argument, fixes #91

---

seml/config.py

None created yet.
The most recent commit e340dc4de0c472839fdda811e8b90d69fd6e54e0 introduces a new way of changing the working directory, when adding config files. 
Unfortunately a bug seems to have sneaked in, when evaluating the `project_root_dir` config variable. This is now evaluated relative to the current working directory of wherever seml was called from and not relative to the config as it was before. This means that if `project_root_dir` was previously set to a valid path when evaluated relative to the config (as in the examples) then this is now broken depending on where seml was called from. At least in my case where I have multiple folders of configuration files this broke all config files.
Evaluating the `project_root_dir` relative to the `config_dir` fixes the bug.

Evaluate project_root_dir relative to config_dir

---

seml/utils.py

None yet.
Hi, this is a bit of a strange bug, but the fix is quite simple.
The dictionaries created from reading in .yaml files can legally contain keys, which are not strings, e.g. integers. However, the current implementation of flatten only handles string keys: https://github.com/TUM-DAML/seml/blob/1ac4b06fcace4014dae5b9ea2d75cdc9c44daf81/seml/utils.py#L125
And thus seml will crash, when adding a config file, which contains integers as keys. With the following error:
```
(seml_pyt-tf) [hborras@ceg-octane sensitivity-metric]$ seml mlp-mapped_test add experiment_configs/MNIST/mlp_mapped_noise_experiment.yaml
Traceback (most recent call last):
File "/home/hborras/.conda/envs/seml_pyt-tf/bin/seml", line 8, in <module> 
sys.exit(main())
File …
```

Add support to flatten dicts with integer keys

---

seml/database.py
seml/main.py
seml/manage.py
setup.py

This PR adds two convenience functions to SEML:
`seml list [pattern]` will list all collections in the database that matches an (optional) RegEx pattern. It will also print the state counts for all experiments in the collection. Note that in contrast to `seml {collection} status`, it does not verify that experiments with state `RUNNING` are actually still running and have not died or been interupted. This is to ensure the command runs quickly.
Example output:
```bash
seml list .*_pneuma
WARNING: Status of RUNNING experiments may not reflect if they have died or been canceled. Use `seml ... status` instead.
+------------+--------+---------+---------+--------+--------+-------------+-----------+-------+
| Collection | STAGED | PENDING | RUNNING | FAILED | KILLED | INTERRUPTED | COMPLETED | …
```

List database and print fail trace

---

docs.md
examples/advanced_example_experiment.py
examples/example_experiment.py
src/seml/__init__.py
src/seml/__main__.py
src/seml/config.py
src/seml/description.py
src/seml/experiment.py
src/seml/manage.py
src/seml/observers.py
src/seml/settings.py
src/seml/start.py
src/seml/utils.py

Here, we group a bunch of standard configurations into a custom Experiment class, which must be used going forward.
This PR has the following breaking changes:
* `seml.experiment.py`'s content is no longer imported by default
* `seml.experiment.Experiment` must be used going forward instead of `sacred.Experiment`
* Some settings were reorganized.
* `seml` will not capture the output of experiments within the MongoDB anymore. To turn this behavior on, either edit your `~/config/seml/settings.py` or create the experiment with `Experiment(capture_output=True)`.
This PR also adds the `print-output` command that pulls the output of the experiment from the slurm log file. If that is not present, it attempts to pull it from the database.

Add sacred.Experiment subclass

---

src/seml/start.py

Added a log message containing a clickable URL to automatically attach a debugger in VSCode. No need to create a launch config every time.
No issue.
If running `seml [collection] start --debug-server`, previously, the IP and port have just been printed to the console.
To attach the debugger in VSCode one had to create a launch configuration every time.
Using the VSCode extension [Debug Launcher](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-debug-launcher) one can create clickable URLs for launch configs.
This PR adds a generator for such a URL and prints it to the console.
I had to hack the logger in order to prevent line breaks due to the limited console width. 
This is **very** unpretty.
If there is a better way, let me know.

VSCode clickable URL to attach debugger

---

src/seml/commands/start.py

Previously, running `seml experiment start --debug-server` threw an IndexError when no experiments were staged. Running `seml experiment start` just printed an info warning. This PR aligns the two behaviors.

Fixes an IndexError when using a debug server without staged experiments
